<div style="border: 5px solid purple; padding: 15px; margin: 5px">
<b> Reviewer's comment</b>
    
Hi, my name is Svetlana (https://hub.tripleten.com/u/855fe797). Congratulations on submitting another project! 🎉
    

Before we start, I want to pay your attention to the color marking:
    

   
    
<div style="border: 5px solid green; padding: 15px; margin: 5px">

Great solutions and ideas that can and should be used in the future are in green comments. Some of them are: 
    
    
- You have successfully prepared the subsets. It is important to split the data correctly in order to ensure there's no intersection;    
          
    
- Used linear regression to make predictions;
    
    
- Calculated profit and estimated risk values; 
    
    
- Wrote a good conclusion! A well-written conclusion shows how the project met its objectives and provides a concise and understandable summary for those who may not have been involved in the details of the project. Good job! 

</div>
    
<div style="border: 5px solid gold; padding: 15px; margin: 5px">
<b> Reviewer's comment </b>

Yellow color indicates what should be optimized. This is not necessary, but it will be great if you make changes to this project. I've left several recommendations throughout the project. 
    
</div>
<div style="border: 5px solid red; padding: 15px; margin: 5px">
<b> Reviewer's comment </b>

Issues that must be corrected to achieve accurate results are indicated in red comments. However, there are no issues that need to be fixed, well done!  

</div>

<hr>

<font color='dodgerblue'>**To sum up:**</font> thank you very much for submitting the project! You did a fantastic job here. You have correctly split the data, explored the distributions, trained several models, and applied the bootstrapping technique. You have successfully estimated profit and conducted risk analysis. You have also compared regions based on risk-adjusted return to make recommendations for further development. Excellent job! I do not have any questions, so the project can be accepted. The next sprints will cover more advanced machine learning methods, I hope you will like it. Good luck! 

    

<hr> 
    
✍️ Here's a nice [article](https://machinelearningmastery.com/a-gentle-introduction-to-the-bootstrap-method/) about the bootstrap method. [This](https://www.youtube.com/watch?v=O_Fj4q8lgmc&list=LL&index=6) is a good video about resampling in bootstrapping.
    

</div>

In [1]:
##Machine Learning in Buisness
#Project Overview
#The goal of this project is to determine the most profitable region for the development of new oil wells. Data from three regions will be analyzed and linear regression models will be trained to predict oil reserves.
#Potential profit and the risk of losses will then be evaluated using bootstrapping. The finalregion will be selected based on the buisness requirement that the risk of losses must be below 2.5%, with preference given to the qualifying region with the highest average profit.
# 1. Data Preparation

<div style="border: 5px solid gold; padding: 10px; margin: 5px">
<b> Reviewer's comment</b>
    
Consider using Markdown cells for your text comments.     
</div>

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [3]:
geo_data_0 = pd.read_csv('/datasets/geo_data_0.csv')
geo_data_1 = pd.read_csv('/datasets/geo_data_1.csv')
geo_data_2 = pd.read_csv('/datasets/geo_data_2.csv')

In [4]:
display(geo_data_0.head())
display(geo_data_1.head())
display(geo_data_2.head())

      id        f0        f1        f2     product
0  txEyH  0.705745 -0.497823  1.221170  105.280062
1  2acmU  1.334711 -0.340164  4.365080   73.037750
2  409Wp  1.022732  0.151990  1.419926   85.265647
3  iJLyR -0.032172  0.139033  2.978566  168.620776
4  Xdl7t  1.988431  0.155413  4.751769  154.036647

      id         f0         f1        f2     product
0  kBEdx -15.001348  -8.276000 -0.005876    3.179103
1  62mP7  14.272088  -3.475083  0.999183   26.953261
2  vyE1P   6.263187  -5.948386  5.001160  134.766305
3  KcrkZ -13.081196 -11.506057  4.999415  137.945408
4  AHL4O  12.702195  -8.147433  5.004363  134.766305

      id        f0        f1        f2     product
0  fwXo0 -1.146987  0.963328 -0.828965   27.758673
1  WJtFt  0.262778  0.269839 -2.530187   56.069697
2  ovLUW  0.194587  0.289035 -5.586433   62.871910
3  q6cA6  2.236060 -0.553760  0.930038  114.572842
4  WPMUX -0.515993  1.716266  5.899011  149.600746

In [5]:
print("Region 0:")
geo_data_0.info()

print("\nRegion 1:")
geo_data_1.info()

print("\nRegion 2:")
geo_data_2.info()

Region 0:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   id       100000 non-null  object
 1   f0       100000 non-null  float64
 2   f1       100000 non-null  float64
 3   f2       100000 non-null  float64
 4   product  100000 non-null  float64
dtypes: float64(4), object(1)
memory usage: 3.8+ MB

Region 1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   id       100000 non-null  object
 1   f0       100000 non-null  float64
 2   f1       100000 non-null  float64
 3   f2       100000 non-null  float64
 4   product  100000 non-null  float64
dtypes: float64(4), object(1)
memory usage: 3.8+ MB

Region 2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   id       100000 non-null  object
 1   f0       100000 non-null  float64
 2   f1       100000 non-null  float64
 3   f2       100000 non-null  float64
 4   product  100000 non-null  float64
dtypes: float64(4), object(1)
memory usage: 3.8+ MB

In [6]:
##Initial Data Inspection
#Each regional dataset contains 100,000 observations and five columns: 'id', 'f0', 'f1', 'f2', and 'product'.
#The three feature columns and the target ('product') are numerical, while 'id' is stored as an object because it contains unique well identifiers. There are no missing values in any of the three datasets.

In [7]:
print("Duplicate rows:")
print("Region 0:", geo_data_0.duplicated().sum())
print("Region 1:", geo_data_1.duplicated().sum())
print("Region 2:", geo_data_2.duplicated().sum())

print("\nDuplicate IDs:")
print("Region 0:", geo_data_0['id'].duplicated().sum())
print("Region 1:", geo_data_1['id'].duplicated().sum())
print("Region 2:", geo_data_2['id'].duplicated().sum())

Duplicate rows:
Region 0: 0
Region 1: 0
Region 2: 0

Duplicate IDs:
Region 0: 10
Region 1: 4
Region 2: 4

In [8]:
##Duplicate Check
#No completely duplicated rows were found in any of the three regional datasets.
#However, the 'id' columns contains some repeated identifiers:
#-Region 0: 10 duplicate IDs
#-Region 1: 4 duplicate IDs
#-Region 2: 4 duplicate IDs
#Since the 'id' column is only an identifier and will not be used as a predictive feature, these rows will be retained.

In [9]:
display(geo_data_0.describe())
display(geo_data_1.describe())
display(geo_data_2.describe())

                  f0             f1             f2        product
count  100000.000000  100000.000000  100000.000000  100000.000000
mean        0.500419       0.250143       2.502647      92.500000
std         0.871832       0.504433       3.248248      44.288691
min        -1.408605      -0.848218     -12.088328       0.000000
25%        -0.072580      -0.200881       0.287748      56.497507
50%         0.502360       0.250252       2.515969      91.849972
75%         1.073581       0.700646       4.715088     128.564089
max         2.362331       1.343769      16.003790     185.364347

                  f0             f1             f2        product
count  100000.000000  100000.000000  100000.000000  100000.000000
mean        1.141296      -4.796579       2.494541      68.825000
std         8.965932       5.119872       1.703572      45.944423
min       -31.609576     -26.358598      -0.018144       0.000000
25%        -6.298551      -8.267985       1.000021      26.953261
50%         1.153055      -4.813172       2.011479      57.085625
75%         8.621015      -1.332816       3.999904     107.813044
max        29.421755      18.734063       5.019721     137.945408

                  f0             f1             f2        product
count  100000.000000  100000.000000  100000.000000  100000.000000
mean        0.002023      -0.002081       2.495128      95.000000
std         1.732045       1.730417       3.473445      44.749921
min        -8.760004      -7.084020     -11.970335       0.000000
25%        -1.162288      -1.174820       0.130359      59.450441
50%         0.009424      -0.009482       2.484236      94.925613
75%         1.158535       1.163678       4.858794     130.595027
max         7.238262       7.844801      16.739402     190.029838

In [10]:
##Descriptive Statistics
#The average volume of oil reserves differs across the three regions:
#-Region 0: 92.50 thousand barrels
#-Region 1: 68.825 thousand barrels
#-Region 2: 95.00 thousand barrels
#Region 2 has the highest average reserve volume, while Region 1 has the lowest. However, average reserves alone are not sufficent for selecting a region. Model predictions, potential profit, and the risk of losses will also need to be evaluated.

<div style="border: 5px solid gold; padding: 10px; margin: 5px">
<b>   Reviewer's comment </b>
    
It will be perfect if you display the charts as well, thus showing a reader why you decided to delete specific rows. Why is this important? In real-world problems, the data is rarely clean. Displaying distributions help us evaluate the data, find outliers, identify the required preprocessing steps and understand feature relationships, which informs feature engineering. Feature engineering in some cases is a clue.


</div>

In [11]:
features_0 = geo_data_0.drop(['id', 'product'], axis=1)
target_0 = geo_data_0['product']

In [12]:
features_train_0, features_valid_0, target_train_0, target_valid_0 = train_test_split(
    features_0,
    target_0,
    test_size=0.25,
    random_state=12345
)

In [13]:
print(features_train_0.shape)
print(features_valid_0.shape)

(75000, 3)
(25000, 3)

In [14]:
##Region 0: Training and Validation Split
#The 'id' column was excluded because it is an identifier and does not provide meaningful information for predicting oil reserves. The 'product' column was seperated as the target, while 'f0', 'f1', and 'f2' were used as features.
#The data was split into a training set containing 75% of the observations and a validation set containing the remaining 25%. Afixed 'random_state' was used to make the split reproducible.

In [15]:
model_0 = LinearRegression()
model_0.fit(features_train_0, target_train_0)
predictions_valid_0 = model_0.predict(features_valid_0)

In [16]:
mean_predicted_0 = predictions_valid_0.mean()
rmse_0 = mean_squared_error(
    target_valid_0,
    predictions_valid_0
) ** 0.5

print("Region 0 average predicted reserves:", mean_predicted_0)
print("Region 0 RMSE:", rmse_0)

Region 0 average predicted reserves: 92.59256778438035
Region 0 RMSE: 37.5794217150813

<div style="border: 5px solid green; padding: 10px; margin: 5px">
<b>   Reviewer's comment </b>
    
Correct!

</div>

In [17]:
##Region 0 Model Results
#The linear regression model predicted an average reserve volume of approximately 92.59 thousand barrels for Region 0.
#The model achieved an RMSE of approximately 37.58 thousand barrels. This indicates that the individualpredictions can differ considerably from the actual reserve volumes. Therefore, although the average predicted reserve is relatively high, the model's prediction error should also be considered when evaluating this region.

In [18]:
features_1 = geo_data_1.drop(['id', 'product'], axis=1)
target_1 = geo_data_1['product']

features_train_1, features_valid_1, target_train_1, target_valid_1 = train_test_split(
    features_1,
    target_1,
    test_size=0.25,
    random_state=12345
)

In [19]:
model_1 = LinearRegression()
model_1.fit(features_train_1, target_train_1)
predictions_valid_1 = model_1.predict(features_valid_1)

In [20]:
mean_predicted_1 = predictions_valid_1.mean()
rmse_1 = mean_squared_error(
    target_valid_1,
    predictions_valid_1
) ** 0.5

print("Region 1 average predicted reserves:", mean_predicted_1)
print("Region 1 RMSE:", rmse_1)

Region 1 average predicted reserves: 68.728546895446
Region 1 RMSE: 0.893099286775617

In [21]:
##Region 1 Model Results
#The linear regression model predicted anaverage reserve volume of approximately 68.73 thousand barrels for Region 1.
#The model achieved an RMSE of approximately 0.89 thousand barrels, which is substantially lower than the RMSE for Region 0. This indicates that the predictions for Region 1 are much more accurate and closely match the actualreserve volumes.

In [22]:
features_2 = geo_data_2.drop(['id', 'product'], axis=1)
target_2 = geo_data_2['product']

features_train_2, features_valid_2, target_train_2, target_valid_2 = train_test_split(
    features_2,
    target_2,
    test_size=0.25,
    random_state=12345
)

model_2 = LinearRegression()
model_2.fit(features_train_2, target_train_2)
predictions_valid_2 = model_2.predict(features_valid_2)

In [23]:
mean_predicted_2 = predictions_valid_2.mean()

rmse_2 = mean_squared_error(
    target_valid_2,
    predictions_valid_2
) ** 0.5

print("Region 2 average predicted reserves:", mean_predicted_2)
print("Region 2 RMSE:", rmse_2)

Region 2 average predicted reserves: 94.96504596800489
Region 2 RMSE: 40.02970873393434

<div style="border: 5px solid gold; padding: 10px; margin: 5px">
<b>   Reviewer's comment </b>
    
You can use a loop or a function, since the code is the same for all three regions. Not only will it make the code  shorter and easier to read, it will help you avoid typos.
</div>

In [24]:
##Region 2 Model Results
#The linear regression model predicted an average reserve volume of approximately 94.97 thousand barrels for Region 2.
#The model achieved an RMSE of approximately 40.03 thousand barrels. Although Region 2 has the highest average predicted reserve volume , its relatively high RMSE indicates considerable prediction error for individual wells.

In [25]:
##Model Training Conclusions
#Region 2 has the highest average predicted reserve volume at approximately 94.97thousand barrels, followed Region 0 at 92.59 thousand barrels. Region 1 has the lowest average predicted reserves at approxiamtely 68.73 thousand barrels.
#However, Region 1 has by far the lowest RMSE at approximately 0.89 thousand barrels, indicating substantially more accurate predictions. Region 0 and 2 have much higher RMSE values of approximately 37.58 and 40.03 thousand barrels, respectively.
#Average predicted reserves and model accuracy alone are not sufficent to select the best region. The potantial profit risk of losses must also be evaluated according to the buisness requirements.

In [26]:
#Buisness parameters

budget = 100_000_000
revenue_per_unit = 4500
num_wells = 200

#Minimum total reserve volume needed to break even
break_even_volume = budget / revenue_per_unit

#Minimum average reserve volume per selected well
break_even_per_well = break_even_volume / num_wells

print("Break-even total reserve volume:", break_even_volume)
print("Break-even reserve volume per well:", break_even_per_well)

Break-even total reserve volume: 22222.222222222223
Break-even reserve volume per well: 111.11111111111111

<div style="border: 5px solid green; padding: 10px; margin: 5px">
<b>   Reviewer's comment </b> 

Correct!
</div>

<div style="border: 5px solid gold; padding: 10px; margin: 5px">
<b> Reviewer's comment </b>
    
Constant values should be defined in the upper case and in the very beginning of the project.  
    
</div>

In [27]:
##Profit Calculation Preparation Conclusions
#The minimum total reserve volume required to avoid losses is approximately 22,222.22 thousand barrels.
#Since 200 wells will be selected for development, each selected well must produce an average of approximately 111.11 thousand barrels to break even.
#The average predicted reserve volumes for all regions are below this break-even amount, so selecting wells based only on the regional average would not be profitable. The 200 wells with the highest predicted reserves must be selected instead.

<div style="border: 5px solid green; padding: 10px; margin: 5px">
<b>   Reviewer's comment </b>
    


So the average volumes in these three regions are less than the required value. If we are to select the wells randomly, we are probably going to lose money. That's why we need machine learning and bootstrapping to estimate profit distributions. 
    
    
</div>

In [28]:
#Variables for profit calculation
budget = 100_000_000
revenue_per_unit = 4500
wells_to_select = 200

In [29]:
def calculate_profit(target, predictions, count):
    predictions_sorted = predictions.sort_values(ascending=False)
    selected = target[predictions_sorted.index][:count]

    revenue = selected.sum() * revenue_per_unit
    profit = revenue - budget

    return profit

<div style="border: 5px solid green; padding: 10px; margin: 5px">
<b>   Reviewer's comment </b>

Correct! We select the best 200 wells by predictions, but then we need to use target values to actually calculate profit because predictions may not be accurate. 

</div>

In [30]:
#Calculate profit for each region

predictions_valid_0 = pd.Series(predictions_valid_0, index=target_valid_0.index)
predictions_valid_1 = pd.Series(predictions_valid_1, index=target_valid_1.index)
predictions_valid_2 = pd.Series(predictions_valid_2, index=target_valid_2.index)

profit_0 = calculate_profit(target_valid_0, predictions_valid_0, wells_to_select)
profit_1 = calculate_profit(target_valid_1, predictions_valid_1, wells_to_select)
profit_2 = calculate_profit(target_valid_2, predictions_valid_2, wells_to_select)

print("Region 0 profit:", profit_0)
print("Region 1 profit:", profit_1)
print("Region 2 profit:", profit_2)

Region 0 profit: 33208260.43139851
Region 1 profit: 24150866.966815114
Region 2 profit: 27103499.635998324

In [31]:
##Profit Calculation Conclusions
#Based on the 200 wells with the highest predicted reserves, all three regions would generate a profit.
#Region 0 has the highest estimated profit at approximately $33.21 million, followed by Region 2 at approximately $27.10 million and Region 1 at approximately $24.15 million
#However, these results alone are not enough to select a region because the risk of losses must also be evaluated using bootstrapping.

In [32]:
##Bootstrapping and Risk Analysis
#Bootstrapping with 1000 samples is used to estimate the distribution of potential profit for each region. For each bootstrap sample, 500 wells are sampled with replacement , and the 200 wells with the highest predicted reserves are selected for profit calculation.
#The average profit, 95% confidence interval, and risk of loss are calculated for each region. A region is considered acceptable only if its risk of loss is below 2.5%

In [33]:
def bootstrap_profit(target, predictions):
    state = np.random.RandomState(12345)
    values = []

    for i in range(1000):
        target_subsample = target.sample(
            n=500,
            replace=True,
            random_state=state
        )

        predictions_subsample = predictions[target_subsample.index]

        profit = calculate_profit(
            target_subsample,
            predictions_subsample,
            wells_to_select
        )

        values.append(profit)

    values = pd.Series(values)

    mean_profit = values.mean()
    lower = values.quantile(0.025)
    upper = values.quantile(0.975)
    risk_of_loss = (values < 0 ).mean() * 100

    return mean_profit, lower, upper, risk_of_loss

In [34]:
mean_profit_0, lower_0, upper_0, risk_of_loss_0 = bootstrap_profit(
    target_valid_0, predictions_valid_0
)
mean_profit_1, lower_1, upper_1, risk_of_loss_1 = bootstrap_profit(
    target_valid_1, predictions_valid_1
)
mean_profit_2, lower_2, upper_2, risk_of_loss_2 = bootstrap_profit(
    target_valid_2, predictions_valid_2
)

print("Region 0 average profit:", mean_profit_0)
print("Region 0 95% confidence interval:", lower_0, upper_0)
print("Region 0 risk of loss:", risk_of_loss_0, "%")

print()

print("Region 1 average profit:", mean_profit_1)
print("Region 1 95% confidence interval:", lower_1, upper_1)
print("Region 1 risk of loss:", risk_of_loss_1, "%")

print()

print("Region 2 average profit:", mean_profit_2)
print("Region 2 95% confidence interval:", lower_2, upper_2)
print("Region 2 risk of loss:", risk_of_loss_2, "%")

Region 0 average profit: 4259385.269105923
Region 0 95% confidence interval: -1020900.9483793724 9479763.533583675
Region 0 risk of loss: 6.0 %

Region 1 average profit: 5152227.734432898
Region 1 95% confidence interval: 688732.2537050088 9315475.912570495
Region 1 risk of loss: 1.0 %

Region 2 average profit: 4350083.627827557
Region 2 95% confidence interval: -1288805.473297878 9697069.541802654
Region 2 risk of loss: 6.4 %

<div style="border: 5px solid green; padding: 10px; margin: 5px">
<b>   Reviewer's comment </b>


There's a replacement, well done! We indeed need to sample points with replacement. The point is that if we remove the replacement, our subsample (or rather, all subsamples) will simply resemble the original sample.
    
</div>

In [35]:
##Bootstrapping Conclusions
#Region 0 has an average estimated profit of approximately $4.26 million with a 6.0% risk of loss.
#Region 1 has an average estimated profit of approximately $5.15 million with a 1.0% risk of loss.
#Region 2 has an average estimated profit of approximately $4.35 million with a 6.4% risk of loss.
#Only Region 1 meets the requirement that the risk of loss must be below 2.5%. Region 1 also has the highest average estimated profit, making it the strongest candidate for development.

In [36]:
##Final Conclusion
#After training linear regression models for all three regions and evaluating potential profits using bootstrapping, Region 1 is the best region for developing new oil wells.
#Region 0 has an average estimated profit of approximately $4.26 million with a 6.0% risk of loss. Region 2 has an average estimated profit of approximately $0.69 million to $9.32 million.
#Therefore, Region 1 is recommended for development because it meets the required risk threshold while also providing the highest expected profit.

<div style="border: 5px solid green; padding: 15px; margin: 5px">
<b>   Reviewer's comment </b>
    

Good conclusion! 

</div>
<div style="border: 5px solid gold; padding: 15px; margin: 5px">
<b>   Reviewer's comment </b>
    

Consider making the final conclusion a bit broader, since this is a conclusion to the whole project. You can briefly outline key results (what has been done) and the conclusions we can draw from these results. 
    
</div>